### ISSUE TITLE
develop

### ISSUE THREAD

**Issue by raymayemir** [gofiber/keyauth#1]
@Fenny Since the jwt middleware supports `<source>:<name>` ,how it is necessary to have a separate key auth middleware ?

or are you trying to replicate all the types of middleware that echo has

**Comment by Fenny** [comment]
Hi @raymayemir, I think someone requested this a month ago. I never picked it up, but we try to replicate all Expressjs middlewares. Some middleware repo's are based on Echo's middleware packages.

`keyauth` is not like JWT, it's mostly handy for api key authentication. I might pick this up later today.

**Comment by raymayemir** [comment]
@Fenny oh yes I didn’t think about that. One more question you will implement everything yourself or still open to other developers and their PR's. If so, to which repositories can I send pr's :)

**Comment by Fenny** [comment]
PR's are always welcome! For new middleware ideas you can open an issue on the official fiber repo. For existing middlewares you can PR anytime!

**Comment by raymayemir** [comment]
ok

**Comment by raymayemir** [comment]
@Fenny Hi! Thank you for adding to the credits :)

But why you doesn't confirm my pr ?
#2 

also, why didn't you add a validator ? Having it on the library side has its advantages as you will not need to constantly check the key or call a function that will check them. I have successfully applied this to my work projects 🤓

**Comment by raymayemir** [comment]
And I have a question about white lists of routes. Why not add this to the configuration, as I did in PR for the JWT middleware ? This would look better than separating paths into those that are used and those that are not restricted

**Comment by zhs** [comment]
Hi, it was a nice idea to have a validator in the library. I use api key in my projects, so I think it would be better to use it from the box.

**Comment by Fenny** [comment]
@raymayemir, thanks for adding the validator https://github.com/gofiber/keyauth/pull/3

Available in `v0.0.3` 👍
